version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: lndmanagej
      POSTGRES_USER: bitcoin
      POSTGRES_PASSWORD: unset
    volumes:
      - postgres-data:/var/lib/postgresql/data
  lnd-managej:
    build:
      context: .
      dockerfile: Dockerfile.compose
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/lndmanagej
      SPRING_DATASOURCE_USERNAME: bitcoin
      SPRING_DATASOURCE_PASSWORD: unset
    ports:
      - "8081:8081"
    volumes:
      - ~/.lnd:/root/.lnd:ro
      - ~/.config/lnd-manageJ.conf:/root/.config/lnd-manageJ.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  postgres-data:
