version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: lndmanagej
      POSTGRES_USER: bitcoin
      POSTGRES_PASSWORD: unset
    volumes:
      - postgres-data:/var/lib/postgresql/data
  lnd-managej:
    build: .
    command: java -jar application/build/libs/application-boot.jar --spring.config.location=classpath:application.properties,/root/override.properties
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/lndmanagej
      SPRING_DATASOURCE_USERNAME: bitcoin
      SPRING_DATASOURCE_PASSWORD: unset
    ports:
      - "8081:8081"
    volumes:
      - ~/.lnd:/root/.lnd:ro
      - ~/.config/lnd-manageJ.conf:/root/.config/lnd-manageJ.conf:ro
volumes:
  postgres-data:
